// Generated by CoffeeScript 1.7.1
(function() {
  var By, Q, driver, glob, should, webdriver;

  Q = require("q");

  should = require("should");

  webdriver = require("selenium-webdriver");

  By = webdriver.By;

  glob = require('glob');

  driver = new webdriver.Builder().usingServer(process.env.SELENIUM_HUB).withCapabilities(webdriver.Capabilities['firefox']()).build();

  driver.manage().timeouts().setScriptTimeout(10000);

  describe("NVD3 Tests", function() {
    var files;
    this.timeout(1000 * 60 * 60);
    files = glob.sync('test/*.html');
    return it("Loads and Runs", function(done) {
      var failed, flows, passed;
      flows = files.map(function(file) {
        var url;
        url = "http://localhost:8808/test/" + (file.match(/.*\/([^\/]+)/)[1]);
        return webdriver.promise.createFlow(function() {
          return driver.get(url).then(function() {
            return console.log("Finished " + url);
          });
        });
      });
      passed = function() {
        console.log("Finished all pages.");
        return driver.quit().then(done);
      };
      failed = function(err) {
        console.error("Had a problem", err);
        return driver.quit().then(function() {
          return done(err);
        });
      };
      return webdriver.promise.fullyResolved(flows).then(passed, failed);
    });
  });

}).call(this);
