// Generated by CoffeeScript 1.7.1
(function() {
  apiTest.config.distribution = {
    ctor: Distribution,
    name: 'distribution',
    parent: 'layer',
    options: ['margin', 'width', 'axis', 'size', 'getData', 'scale', 'color', 'duration'],
    dispatch: true,
    optionsFunc: true,
    events: ['renderEnd']
  };

  apiTest.run('distribution');

}).call(this);
