// Generated by CoffeeScript 1.7.1
(function() {
  apiTest.config.sparkline = {
    ctor: Sparkline,
    name: 'sparkline',
    parent: 'layer',
    options: ['margin', 'width', 'height', 'x', 'y', 'xScale', 'yScale', 'xDomain', 'yDomain', 'xRange', 'yRange', 'animate', 'color'],
    dispatch: true,
    optionsFunc: true,
    events: ['elementClick', 'elementMouseover', 'elementMouseout', 'renderEnd']
  };

  apiTest.run('sparkline');

}).call(this);
