// Generated by CoffeeScript 1.7.1
(function() {
  apiTest.config.sparklinePlus = {
    ctor: SparklinePlus,
    name: 'sparklinePlus',
    parent: 'chart',
    options: ['margin', 'width', 'height', 'xTickFormat', 'yTickFormat', 'showValue', 'alignValue', 'rightAlignValue'],
    submodels: {
      sparkline: nv.models.sparkline
    },
    inheritedInstance: {
      sparkline: ['x', 'y', 'xScale', 'yScale', 'color']
    },
    dispatch: true,
    optionsFunc: true,
    events: ['tooltipShow', 'tooltipHide', 'stateChange', 'changeState', 'renderEnd']
  };

}).call(this);
