// Generated by CoffeeScript 1.7.1
(function() {
  var apiTest, should;

  should = chai.should();

  apiTest = apiTest || {};

  apiTest.models.chart = function(instance, overrides) {
    var options;
    if (overrides == null) {
      overrides = [];
    }
    options = ['showXAxis', 'showYAxis', 'rightAlignYAxis', 'reduceXTicks', 'noData', 'tooltips', 'tooltipContent'];
    describe('Inherited API', function() {
      return apiTest.models.layer(instance, overrides);
    });
    return describe('Chart API', function() {
      return checkProperties({
        instance: instance,
        properties: options,
        overrides: overrides,
        parent: Chart
      });
    });
  };

  describe('Chart Model', function() {
    return apiTest.models.chart(new Chart());
  });

}).call(this);
