// Generated by CoffeeScript 1.7.1
(function() {
  var apiTest, should;

  should = chai.should();

  apiTest = apiTest || {};

  apiTest.interactiveGuideline = function(instance, overrides) {
    var options;
    if (overrides == null) {
      overrides = [];
    }
    options = ['margin', 'width', 'height', 'xScale', 'showGuideLine', 'svgContainer', 'renderGuideLine'];
    return describe('InteractiveGuideline API', function() {
      return checkProperties({
        instance: instance,
        properties: options,
        overrides: overrides,
        parent: InteractiveGuideline
      });
    });
  };

  describe('InteractiveGuideline Model', function() {
    return apiTest.interactiveGuideline(nv.interactiveGuideline());
  });

}).call(this);
